version: "3"
services:
  ngrok:
    image: wernight/ngrok
    command: ngrok http agent:3000 --log stdout
  agent:
    build: .
    environment:
      NGROK_NAME: ngrok
      AGENT_NAME: Berend
      PORT: 3000
      ADMIN_PORT: 3001
    ports:
      - "3001:3001"
